# CMake generated Testfile for 
# Source directory: /Users/trung/cpp_vrml_utility/modules/cli11/tests
# Build directory: /Users/trung/cpp_vrml_utility/modules/cli11/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[HelpersTest]=] "HelpersTest")
set_tests_properties([=[HelpersTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[ConfigFileTest]=] "ConfigFileTest")
set_tests_properties([=[ConfigFileTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[OptionTypeTest]=] "OptionTypeTest")
set_tests_properties([=[OptionTypeTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[SimpleTest]=] "SimpleTest")
set_tests_properties([=[SimpleTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[AppTest]=] "AppTest")
set_tests_properties([=[AppTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[SetTest]=] "SetTest")
set_tests_properties([=[SetTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[TransformTest]=] "TransformTest")
set_tests_properties([=[TransformTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[CreationTest]=] "CreationTest")
set_tests_properties([=[CreationTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[SubcommandTest]=] "SubcommandTest")
set_tests_properties([=[SubcommandTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[HelpTest]=] "HelpTest")
set_tests_properties([=[HelpTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[FormatterTest]=] "FormatterTest")
set_tests_properties([=[FormatterTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[NewParseTest]=] "NewParseTest")
set_tests_properties([=[NewParseTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[OptionalTest]=] "OptionalTest")
set_tests_properties([=[OptionalTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[DeprecatedTest]=] "DeprecatedTest")
set_tests_properties([=[DeprecatedTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[StringParseTest]=] "StringParseTest")
set_tests_properties([=[StringParseTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[ComplexTypeTest]=] "ComplexTypeTest")
set_tests_properties([=[ComplexTypeTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[TrueFalseTest]=] "TrueFalseTest")
set_tests_properties([=[TrueFalseTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[OptionGroupTest]=] "OptionGroupTest")
set_tests_properties([=[OptionGroupTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[EncodingTest]=] "EncodingTest")
set_tests_properties([=[EncodingTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;164;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[TimerTest]=] "TimerTest")
set_tests_properties([=[TimerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;180;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
add_test([=[link_test_2]=] "link_test_2")
set_tests_properties([=[link_test_2]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;142;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;207;add_catch_test;/Users/trung/cpp_vrml_utility/modules/cli11/tests/CMakeLists.txt;0;")
