# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.28.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.28.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/trung/cpp_vrml_utility

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/trung/cpp_vrml_utility

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.28.1/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.28.1/bin/cpack --config ./CPackSourceConfig.cmake /Users/trung/cpp_vrml_utility/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.28.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.28.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.28.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.28.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/trung/cpp_vrml_utility/CMakeFiles /Users/trung/cpp_vrml_utility//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/trung/cpp_vrml_utility/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named g4_replace_structure_value

# Build rule for target.
g4_replace_structure_value: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 g4_replace_structure_value
.PHONY : g4_replace_structure_value

# fast build rule for target.
g4_replace_structure_value/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/build
.PHONY : g4_replace_structure_value/fast

#=============================================================================
# Target rules for targets named g4_gamoslog_to_cubic

# Build rule for target.
g4_gamoslog_to_cubic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 g4_gamoslog_to_cubic
.PHONY : g4_gamoslog_to_cubic

# fast build rule for target.
g4_gamoslog_to_cubic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/build
.PHONY : g4_gamoslog_to_cubic/fast

#=============================================================================
# Target rules for targets named CLI11

# Build rule for target.
CLI11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CLI11
.PHONY : CLI11

# fast build rule for target.
CLI11/fast:
	$(MAKE) $(MAKESILENT) -f modules/cli11/src/CMakeFiles/CLI11.dir/build.make modules/cli11/src/CMakeFiles/CLI11.dir/build
.PHONY : CLI11/fast

src/common/FileUtils.o: src/common/FileUtils.cpp.o
.PHONY : src/common/FileUtils.o

# target to build an object file
src/common/FileUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/common/FileUtils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/common/FileUtils.cpp.o
.PHONY : src/common/FileUtils.cpp.o

src/common/FileUtils.i: src/common/FileUtils.cpp.i
.PHONY : src/common/FileUtils.i

# target to preprocess a source file
src/common/FileUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/common/FileUtils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/common/FileUtils.cpp.i
.PHONY : src/common/FileUtils.cpp.i

src/common/FileUtils.s: src/common/FileUtils.cpp.s
.PHONY : src/common/FileUtils.s

# target to generate assembly for a file
src/common/FileUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/common/FileUtils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/common/FileUtils.cpp.s
.PHONY : src/common/FileUtils.cpp.s

src/common/StringUtils.o: src/common/StringUtils.cpp.o
.PHONY : src/common/StringUtils.o

# target to build an object file
src/common/StringUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/common/StringUtils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/common/StringUtils.cpp.o
.PHONY : src/common/StringUtils.cpp.o

src/common/StringUtils.i: src/common/StringUtils.cpp.i
.PHONY : src/common/StringUtils.i

# target to preprocess a source file
src/common/StringUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/common/StringUtils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/common/StringUtils.cpp.i
.PHONY : src/common/StringUtils.cpp.i

src/common/StringUtils.s: src/common/StringUtils.cpp.s
.PHONY : src/common/StringUtils.s

# target to generate assembly for a file
src/common/StringUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/common/StringUtils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/common/StringUtils.cpp.s
.PHONY : src/common/StringUtils.cpp.s

src/common/VRML.o: src/common/VRML.cpp.o
.PHONY : src/common/VRML.o

# target to build an object file
src/common/VRML.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/common/VRML.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/common/VRML.cpp.o
.PHONY : src/common/VRML.cpp.o

src/common/VRML.i: src/common/VRML.cpp.i
.PHONY : src/common/VRML.i

# target to preprocess a source file
src/common/VRML.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/common/VRML.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/common/VRML.cpp.i
.PHONY : src/common/VRML.cpp.i

src/common/VRML.s: src/common/VRML.cpp.s
.PHONY : src/common/VRML.s

# target to generate assembly for a file
src/common/VRML.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/common/VRML.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/common/VRML.cpp.s
.PHONY : src/common/VRML.cpp.s

src/function/G4DCM.o: src/function/G4DCM.cpp.o
.PHONY : src/function/G4DCM.o

# target to build an object file
src/function/G4DCM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/function/G4DCM.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/function/G4DCM.cpp.o
.PHONY : src/function/G4DCM.cpp.o

src/function/G4DCM.i: src/function/G4DCM.cpp.i
.PHONY : src/function/G4DCM.i

# target to preprocess a source file
src/function/G4DCM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/function/G4DCM.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/function/G4DCM.cpp.i
.PHONY : src/function/G4DCM.cpp.i

src/function/G4DCM.s: src/function/G4DCM.cpp.s
.PHONY : src/function/G4DCM.s

# target to generate assembly for a file
src/function/G4DCM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/function/G4DCM.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/function/G4DCM.cpp.s
.PHONY : src/function/G4DCM.cpp.s

src/function/Gamos_Log.o: src/function/Gamos_Log.cpp.o
.PHONY : src/function/Gamos_Log.o

# target to build an object file
src/function/Gamos_Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/function/Gamos_Log.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/function/Gamos_Log.cpp.o
.PHONY : src/function/Gamos_Log.cpp.o

src/function/Gamos_Log.i: src/function/Gamos_Log.cpp.i
.PHONY : src/function/Gamos_Log.i

# target to preprocess a source file
src/function/Gamos_Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/function/Gamos_Log.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/function/Gamos_Log.cpp.i
.PHONY : src/function/Gamos_Log.cpp.i

src/function/Gamos_Log.s: src/function/Gamos_Log.cpp.s
.PHONY : src/function/Gamos_Log.s

# target to generate assembly for a file
src/function/Gamos_Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/function/Gamos_Log.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/function/Gamos_Log.cpp.s
.PHONY : src/function/Gamos_Log.cpp.s

src/function/WRLHelper.o: src/function/WRLHelper.cpp.o
.PHONY : src/function/WRLHelper.o

# target to build an object file
src/function/WRLHelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/function/WRLHelper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/function/WRLHelper.cpp.o
.PHONY : src/function/WRLHelper.cpp.o

src/function/WRLHelper.i: src/function/WRLHelper.cpp.i
.PHONY : src/function/WRLHelper.i

# target to preprocess a source file
src/function/WRLHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/function/WRLHelper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/function/WRLHelper.cpp.i
.PHONY : src/function/WRLHelper.cpp.i

src/function/WRLHelper.s: src/function/WRLHelper.cpp.s
.PHONY : src/function/WRLHelper.s

# target to generate assembly for a file
src/function/WRLHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/function/WRLHelper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/function/WRLHelper.cpp.s
.PHONY : src/function/WRLHelper.cpp.s

src/g4_gamoslog_to_cubic.o: src/g4_gamoslog_to_cubic.cpp.o
.PHONY : src/g4_gamoslog_to_cubic.o

# target to build an object file
src/g4_gamoslog_to_cubic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/g4_gamoslog_to_cubic.cpp.o
.PHONY : src/g4_gamoslog_to_cubic.cpp.o

src/g4_gamoslog_to_cubic.i: src/g4_gamoslog_to_cubic.cpp.i
.PHONY : src/g4_gamoslog_to_cubic.i

# target to preprocess a source file
src/g4_gamoslog_to_cubic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/g4_gamoslog_to_cubic.cpp.i
.PHONY : src/g4_gamoslog_to_cubic.cpp.i

src/g4_gamoslog_to_cubic.s: src/g4_gamoslog_to_cubic.cpp.s
.PHONY : src/g4_gamoslog_to_cubic.s

# target to generate assembly for a file
src/g4_gamoslog_to_cubic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_gamoslog_to_cubic.dir/build.make CMakeFiles/g4_gamoslog_to_cubic.dir/src/g4_gamoslog_to_cubic.cpp.s
.PHONY : src/g4_gamoslog_to_cubic.cpp.s

src/g4_replace_structure_value.o: src/g4_replace_structure_value.cpp.o
.PHONY : src/g4_replace_structure_value.o

# target to build an object file
src/g4_replace_structure_value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/g4_replace_structure_value.cpp.o
.PHONY : src/g4_replace_structure_value.cpp.o

src/g4_replace_structure_value.i: src/g4_replace_structure_value.cpp.i
.PHONY : src/g4_replace_structure_value.i

# target to preprocess a source file
src/g4_replace_structure_value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/g4_replace_structure_value.cpp.i
.PHONY : src/g4_replace_structure_value.cpp.i

src/g4_replace_structure_value.s: src/g4_replace_structure_value.cpp.s
.PHONY : src/g4_replace_structure_value.s

# target to generate assembly for a file
src/g4_replace_structure_value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/g4_replace_structure_value.dir/build.make CMakeFiles/g4_replace_structure_value.dir/src/g4_replace_structure_value.cpp.s
.PHONY : src/g4_replace_structure_value.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... CLI11"
	@echo "... g4_gamoslog_to_cubic"
	@echo "... g4_replace_structure_value"
	@echo "... src/common/FileUtils.o"
	@echo "... src/common/FileUtils.i"
	@echo "... src/common/FileUtils.s"
	@echo "... src/common/StringUtils.o"
	@echo "... src/common/StringUtils.i"
	@echo "... src/common/StringUtils.s"
	@echo "... src/common/VRML.o"
	@echo "... src/common/VRML.i"
	@echo "... src/common/VRML.s"
	@echo "... src/function/G4DCM.o"
	@echo "... src/function/G4DCM.i"
	@echo "... src/function/G4DCM.s"
	@echo "... src/function/Gamos_Log.o"
	@echo "... src/function/Gamos_Log.i"
	@echo "... src/function/Gamos_Log.s"
	@echo "... src/function/WRLHelper.o"
	@echo "... src/function/WRLHelper.i"
	@echo "... src/function/WRLHelper.s"
	@echo "... src/g4_gamoslog_to_cubic.o"
	@echo "... src/g4_gamoslog_to_cubic.i"
	@echo "... src/g4_gamoslog_to_cubic.s"
	@echo "... src/g4_replace_structure_value.o"
	@echo "... src/g4_replace_structure_value.i"
	@echo "... src/g4_replace_structure_value.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

