# CMake generated Testfile for 
# Source directory: /Users/trung/cpp_vrml_utility/modules/cli11/examples
# Build directory: /Users/trung/cpp_vrml_utility/modules/cli11/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[simple_basic]=] "/Users/trung/cpp_vrml_utility/dist/simple")
set_tests_properties([=[simple_basic]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;39;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[simple_all]=] "/Users/trung/cpp_vrml_utility/dist/simple" "-f" "filename.txt" "-c" "12" "--flag" "--flag" "-d" "1.2")
set_tests_properties([=[simple_all]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Working on file: filename.txt, direct count: 1, opt count: 1;Working on count: 12, direct count: 1, opt count: 1;Received flag: 2 (2) times;Some value: 1.2" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;40;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[simple_version]=] "/Users/trung/cpp_vrml_utility/dist/simple" "--version")
set_tests_properties([=[simple_version]=] PROPERTIES  PASS_REGULAR_EXPRESSION "2.3.2" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;47;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[subcommands_none]=] "/Users/trung/cpp_vrml_utility/dist/subcommands")
set_tests_properties([=[subcommands_none]=] PROPERTIES  PASS_REGULAR_EXPRESSION "A subcommand is required" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;51;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[subcommands_all]=] "/Users/trung/cpp_vrml_utility/dist/subcommands" "--random" "start" "--file" "name" "stop" "--count")
set_tests_properties([=[subcommands_all]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Working on --file from start: name;Working on --count from stop: 1, direct count: 1;Count of --random flag: 1;Subcommand: start;Subcommand: stop" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;53;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[subcom_partitioned_none]=] "/Users/trung/cpp_vrml_utility/dist/subcom_partitioned")
set_tests_properties([=[subcom_partitioned_none]=] PROPERTIES  PASS_REGULAR_EXPRESSION "This is a timer:;--file is required;Run with --help for more information." _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;64;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[subcom_partitioned_all]=] "/Users/trung/cpp_vrml_utility/dist/subcom_partitioned" "--file" "this" "--count" "--count" "-d" "1.2")
set_tests_properties([=[subcom_partitioned_all]=] PROPERTIES  PASS_REGULAR_EXPRESSION "This is a timer:;Working on file: this, direct count: 1, opt count: 1;Working on count: 2, direct count: 2, opt count: 2;Some value: 1.2" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;70;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[subcom_partitioned_help]=] "/Users/trung/cpp_vrml_utility/dist/subcom_partitioned" "--help")
set_tests_properties([=[subcom_partitioned_help]=] PROPERTIES  PASS_REGULAR_EXPRESSION "-f,--file TEXT REQUIRED;-d,--double FLOAT" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;77;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[config_app1]=] "/Users/trung/cpp_vrml_utility/dist/config_app" "-p")
set_tests_properties([=[config_app1]=] PROPERTIES  PASS_REGULAR_EXPRESSION "file=" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;83;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[config_app2]=] "/Users/trung/cpp_vrml_utility/dist/config_app" "-p" "-f" "/")
set_tests_properties([=[config_app2]=] PROPERTIES  PASS_REGULAR_EXPRESSION "file=\"/\"" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;86;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[config_app3]=] "/Users/trung/cpp_vrml_utility/dist/config_app" "-f" "" "-p")
set_tests_properties([=[config_app3]=] PROPERTIES  PASS_REGULAR_EXPRESSION "file=\"\"" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;89;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[config_app4]=] "/Users/trung/cpp_vrml_utility/dist/config_app" "-f" "/" "-p")
set_tests_properties([=[config_app4]=] PROPERTIES  PASS_REGULAR_EXPRESSION "file=\"/\"" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;92;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[option_groups_missing]=] "/Users/trung/cpp_vrml_utility/dist/option_groups")
set_tests_properties([=[option_groups_missing]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Exactly 1 option from;is required" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;98;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[option_groups_extra]=] "/Users/trung/cpp_vrml_utility/dist/option_groups" "--csv" "--binary")
set_tests_properties([=[option_groups_extra]=] PROPERTIES  PASS_REGULAR_EXPRESSION "and 2 were given" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;101;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[option_groups_extra2]=] "/Users/trung/cpp_vrml_utility/dist/option_groups" "--csv" "--address" "192.168.1.1" "-o" "test.out")
set_tests_properties([=[option_groups_extra2]=] PROPERTIES  PASS_REGULAR_EXPRESSION "at most 1" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;103;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[positional_arity1]=] "/Users/trung/cpp_vrml_utility/dist/positional_arity" "one")
set_tests_properties([=[positional_arity1]=] PROPERTIES  PASS_REGULAR_EXPRESSION "File 1 = one" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;108;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[positional_arity2]=] "/Users/trung/cpp_vrml_utility/dist/positional_arity" "one" "two")
set_tests_properties([=[positional_arity2]=] PROPERTIES  PASS_REGULAR_EXPRESSION "File 1 = one;File 2 = two" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;110;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[positional_arity3]=] "/Users/trung/cpp_vrml_utility/dist/positional_arity" "1" "2" "one")
set_tests_properties([=[positional_arity3]=] PROPERTIES  PASS_REGULAR_EXPRESSION "File 1 = one" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;112;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[positional_arity_fail]=] "/Users/trung/cpp_vrml_utility/dist/positional_arity" "1" "one" "two")
set_tests_properties([=[positional_arity_fail]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Could not convert" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;114;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[positional_validation1]=] "/Users/trung/cpp_vrml_utility/dist/positional_validation" "one")
set_tests_properties([=[positional_validation1]=] PROPERTIES  PASS_REGULAR_EXPRESSION "File 1 = one" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;118;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[positional_validation2]=] "/Users/trung/cpp_vrml_utility/dist/positional_validation" "one" "1" "2" "two")
set_tests_properties([=[positional_validation2]=] PROPERTIES  PASS_REGULAR_EXPRESSION "File 1 = one;File 2 = two" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;120;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[positional_validation3]=] "/Users/trung/cpp_vrml_utility/dist/positional_validation" "1" "2" "one")
set_tests_properties([=[positional_validation3]=] PROPERTIES  PASS_REGULAR_EXPRESSION "File 1 = one" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;123;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[positional_validation4]=] "/Users/trung/cpp_vrml_utility/dist/positional_validation" "1" "one" "two" "2")
set_tests_properties([=[positional_validation4]=] PROPERTIES  PASS_REGULAR_EXPRESSION "File 1 = one;File 2 = two" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;125;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[shapes_all]=] "/Users/trung/cpp_vrml_utility/dist/shapes" "circle" "4.4" "circle" "10.7" "rectangle" "4" "4" "circle" "2.3" "triangle" "4.5" "++" "rectangle" "2.1" "++" "circle" "234.675")
set_tests_properties([=[shapes_all]=] PROPERTIES  PASS_REGULAR_EXPRESSION "circle2;circle4;rectangle2 with edges [2.1,2.1];triangel1 with sides [4.5]" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;130;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[ranges_range]=] "/Users/trung/cpp_vrml_utility/dist/ranges" "--range" "1" "2" "3")
set_tests_properties([=[ranges_range]=] PROPERTIES  PASS_REGULAR_EXPRESSION "[2:1:3]" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;137;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[ranges_minmax]=] "/Users/trung/cpp_vrml_utility/dist/ranges" "--min" "2" "--max" "3")
set_tests_properties([=[ranges_minmax]=] PROPERTIES  PASS_REGULAR_EXPRESSION "[2:1:3]" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;139;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[ranges_error]=] "/Users/trung/cpp_vrml_utility/dist/ranges" "--min" "2" "--max" "3" "--step" "1" "--range" "1" "2" "3")
set_tests_properties([=[ranges_error]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Exactly 1 option from" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;141;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[validators_help]=] "/Users/trung/cpp_vrml_utility/dist/validators" "--help")
set_tests_properties([=[validators_help]=] PROPERTIES  PASS_REGULAR_EXPRESSION "  -f,--file TEXT:FILE[\\r\\n\\t ]+File name;  -v,--value INT:INT in [3 - 6][\\r\\n\\t ]+Value in range" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;145;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[validators_file]=] "/Users/trung/cpp_vrml_utility/dist/validators" "--file" "nonex.xxx")
set_tests_properties([=[validators_file]=] PROPERTIES  PASS_REGULAR_EXPRESSION "--file: File does not exist: nonex.xxx;Run with --help for more information." _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;150;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[validators_plain]=] "/Users/trung/cpp_vrml_utility/dist/validators" "--value" "9")
set_tests_properties([=[validators_plain]=] PROPERTIES  PASS_REGULAR_EXPRESSION "--value: Value 9 not in range 3 to 6;Run with --help for more information." _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;154;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[groups_none]=] "/Users/trung/cpp_vrml_utility/dist/groups")
set_tests_properties([=[groups_none]=] PROPERTIES  PASS_REGULAR_EXPRESSION "This is a timer:;--file is required;Run with --help for more information." _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;160;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[groups_all]=] "/Users/trung/cpp_vrml_utility/dist/groups" "--file" "this" "--count" "--count" "-d" "1.2")
set_tests_properties([=[groups_all]=] PROPERTIES  PASS_REGULAR_EXPRESSION "This is a timer:;Working on file: this, direct count: 1, opt count: 1;Working on count: 2, direct count: 2, opt count: 2;Some value: 1.2" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;164;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[inter_argument_order]=] "/Users/trung/cpp_vrml_utility/dist/inter_argument_order" "--foo" "1" "2" "3" "--x" "--bar" "4" "5" "6" "--z" "--foo" "7" "8")
set_tests_properties([=[inter_argument_order]=] PROPERTIES  PASS_REGULAR_EXPRESSION "foo : 1
foo : 2
foo : 3
bar : 4
bar : 5
bar : 6
foo : 7
foo : 8" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;172;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[prefix_command]=] "/Users/trung/cpp_vrml_utility/dist/prefix_command" "-v" "3" "2" "1" "--" "other" "one" "two" "3")
set_tests_properties([=[prefix_command]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Prefix: 3 : 2 : 1;Remaining commands: other one two 3" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;188;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[arg_capture]=] "/Users/trung/cpp_vrml_utility/dist/arg_capture" "-v" "27" "--sub" "-v" "13" "--val" "prefix")
set_tests_properties([=[arg_capture]=] PROPERTIES  PASS_REGULAR_EXPRESSION "value=27" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;193;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[arg_capture2]=] "/Users/trung/cpp_vrml_utility/dist/arg_capture" "-v" "27" "--sub" "-v" "13" "--val" "prefix")
set_tests_properties([=[arg_capture2]=] PROPERTIES  PASS_REGULAR_EXPRESSION "after Args:-v 13 --val prefix" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;195;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[callback_passthrough1]=] "/Users/trung/cpp_vrml_utility/dist/callback_passthrough" "--argname" "t2" "--t2" "test")
set_tests_properties([=[callback_passthrough1]=] PROPERTIES  PASS_REGULAR_EXPRESSION "the value is now test" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;199;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[callback_passthrough2]=] "/Users/trung/cpp_vrml_utility/dist/callback_passthrough" "--arg" "EEEK" "--argname" "arg")
set_tests_properties([=[callback_passthrough2]=] PROPERTIES  PASS_REGULAR_EXPRESSION "the value is now EEEK" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;201;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[enum_pass]=] "/Users/trung/cpp_vrml_utility/dist/enum" "-l" "1")
set_tests_properties([=[enum_pass]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;205;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[enum_fail]=] "/Users/trung/cpp_vrml_utility/dist/enum" "-l" "4")
set_tests_properties([=[enum_fail]=] PROPERTIES  PASS_REGULAR_EXPRESSION "--level: Check 4 value in {;FAILED" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;206;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[enum_ostream_pass]=] "/Users/trung/cpp_vrml_utility/dist/enum_ostream" "--level" "medium")
set_tests_properties([=[enum_ostream_pass]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Enum received: Medium" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;211;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[digit_args]=] "/Users/trung/cpp_vrml_utility/dist/digit_args" "-h")
set_tests_properties([=[digit_args]=] PROPERTIES  PASS_REGULAR_EXPRESSION "-3{3}" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;215;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[modhelp]=] "/Users/trung/cpp_vrml_utility/dist/modhelp" "-a" "test" "-h")
set_tests_properties([=[modhelp]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Option -a string in help: test" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;219;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[subcom_in_files]=] "/Users/trung/cpp_vrml_utility/dist/subcommand_main" "subcommand_a" "-f" "this.txt" "--with-foo")
set_tests_properties([=[subcom_in_files]=] PROPERTIES  PASS_REGULAR_EXPRESSION "Working on file: this.txt;Using foo!" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;223;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[subcom_help_normal]=] "/Users/trung/cpp_vrml_utility/dist/subcom_help" "sub" "--help")
set_tests_properties([=[subcom_help_normal]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;232;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[subcom_help_reversed]=] "/Users/trung/cpp_vrml_utility/dist/subcom_help" "--help" "sub")
set_tests_properties([=[subcom_help_reversed]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;233;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[retired_retired_test]=] "/Users/trung/cpp_vrml_utility/dist/retired" "--retired_option")
set_tests_properties([=[retired_retired_test]=] PROPERTIES  PASS_REGULAR_EXPRESSION "WARNING.*retired" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;236;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[retired_retired_test2]=] "/Users/trung/cpp_vrml_utility/dist/retired" "--retired_option" "567")
set_tests_properties([=[retired_retired_test2]=] PROPERTIES  PASS_REGULAR_EXPRESSION "WARNING.*retired" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;237;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[retired_retired_test3]=] "/Users/trung/cpp_vrml_utility/dist/retired" "--retired_option2" "567" "689" "789")
set_tests_properties([=[retired_retired_test3]=] PROPERTIES  PASS_REGULAR_EXPRESSION "WARNING.*retired" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;238;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[retired_deprecated]=] "/Users/trung/cpp_vrml_utility/dist/retired" "--deprecate" "19" "20")
set_tests_properties([=[retired_deprecated]=] PROPERTIES  PASS_REGULAR_EXPRESSION "deprecated.*not_deprecated" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;239;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
add_test([=[cp_test]=] "/Users/trung/cpp_vrml_utility/dist/custom_parse" "--dv" "1.7")
set_tests_properties([=[cp_test]=] PROPERTIES  PASS_REGULAR_EXPRESSION "called correct" _BACKTRACE_TRIPLES "/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;251;add_test;/Users/trung/cpp_vrml_utility/modules/cli11/examples/CMakeLists.txt;0;")
subdirs("subcom_in_files")
